config/routes.rb
Skillz::Application.routes.draw do

  root :to => 'skills#index'

  match 'about' => 'skills#about', as: "about"
  match 'faq' => 'skills#faq', as: "faq"
  match 'csv' => 'skills#csv', as: "csv"
  match 'save' => 'skills#save', as: "save"
  match 'change' => 'skills#change', as: "change"
  match 'save_comment' => 'skills#save_comment', as: "save_comment"
  match 'comments' => 'skills#comments', as: "comments"
  match 'activity' => 'skills#activity', as: "activity"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Skillz" %><%= " (local)" if Rails.env.development? %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

</head>
<body>

<%
   editable = @self_user.present? && @current_user.present? && @self_user.id == @current_user.id
   full_name = @current_user.present? ? "#{@current_user.first_name} #{@current_user.last_name}" : "Choose Person..."
   first_name = @current_user.present? ? @current_user.first_name : ""
   email = @current_user.present? ? @current_user.email : ""
   title = @current_user.present? ? "Show skills for #{full_name}" : ""
%>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">

      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="btn-group btn-user pull-right">

        <a class="btn person <%= "no_current toggle_form" unless @current_user.present? %>" href="<%= @current_user.present? ? root_path : "#" %>" title="<%= title %>">
          <i class="icon-user"></i>
          <strong><%= full_name %></strong>
        </a>

        <% if @current_user.present? %>
          <a class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </a>
        <% else %>
          <a class="btn dropdown-toggle toggle_form" href="#">
            <span>&nbsp;</span>
          </a>
        <% end %>

        <ul class="dropdown-menu">
          <li class="change"><a class="toggle_form" href="#" title="See other people's skills"><small>View somebody else...</small></a></li>
          <% if @self_user.present? && @current_user.present? %>
            <% if @self_user.id == @current_user.id %>
              <li class="disabled"><a><small>This is you</small></a></li>
            <% else %>
              <li class="go_self"><a href="<%= change_path(q: @self_user.email) %>" title="View and edit your own skills"><small>Go to <%= "#{@self_user.first_name} #{@self_user.last_name}" %></small><small class="muted">  (you)</small></a></li>
            <% end %>
          <% end %>
          <li class="divider"></li>
          <% if editable %>
            <li class="self_user"><a href="<%= change_path(q: email, s: "") %>" title="Disallow editing for <%= full_name %>"><small>I'm not <%= first_name %></small></a></li>
          <% else %>
            <li class="self_user"><a href="<%= change_path(q: email, s: email) %>" title="Allow editing for <%= full_name %>"><small>I'm <%= first_name %></small></a></li>
          <% end %>
        </ul>

      </div>

      <%= render partial: "skills/person_form" %>

      <a class="brand hidden-phone" href="<%= about_path %>" title="Got Skillz">Skillz</a>

      <br>

      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <li><a href="<%= csv_path %>" title="Export info to a CSV file"><small>Export</small></a></li>
          <li><a href="<%= comments_path %>" title="Comments from users"><small>Comments</small></a></li>
          <li><a href="<%= activity_path %>" title="View recent activity"><small>Activity</small></a></li>
          <li><a href="<%= faq_path %>" title="Frequently Asked Questions"><small>FAQ</small></a></li>
          <li><a href="<%= about_path %>" title="About the Skillz project"><small>About</small></a></li>
        </ul>
      </div><!--/.nav-collapse -->

    </div>
  </div>
</div>

<div class="container-fluid">

  <div class="row-fluid">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <%= render partial: "skills/comment_form" %>
    <p class="copyright small muted">&copy; Nomad Ninjas 201<span>3</span></p>
  </footer>

</div> <!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script type="text/javascript">
  var skillzUser = '<%= @current_user.email.html_safe if @current_user.present? %>';
  var skillzUsers = <%= User.select("first_name, last_name").order("last_name, first_name").all.to_json.html_safe %>;
  var skills = <%= Skill.select("code, label, parent, parents").order("sort_order").all.to_json.html_safe %>;
</script>

<%= javascript_include_tag "application" %>

  <div class="overlay"></div>

</body>
</html>

app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Skillz" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Skillz</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>